### ISSUE TITLE
No longer getting a response back -- potentially after Ecovacs app update

### ISSUE THREAD

**Issue by sh00t2kill** [Ligio/ozmo#15]
Using an ozmo 900/905. Im not sure exactly when it stopped working as my vacuum was offline for a little while waiting for a new battery.

```Error while setting up deebot platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deebot/vacuum.py", line 46, in setup_platform
    vacuums.append(EcovacsDeebotVacuum(device, hass.data[ECOVACS_CONFIG][0]))
  File "/config/custom_components/deebot/vacuum.py", line 59, in __init__
    self.device.connect_and_wait_until_ready()
  File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 461, in connect_and_wait_until_ready                                                                                                         self.send_ping()                                                                                                                                                                                               File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 628, in send_ping                                                                                                                            self.request_all_statuses()                                                                                                                                                                                    File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 662, in request_all_statuses                                                                                                                 self.refresh_statuses()                                                                                                                                                                                        File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 647, in refresh_statuses
    self.run(GetCleanState())                                                                                                                                                                                      File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 673, in run
    self.send_command(action)
  File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 670, in send_command
    self.iotmq.send_command(action, self._vacuum_address())  #IOTMQ devices need the full action for additional parsing
  File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 789, in send_command
    self._handle_ctl_api(
  File "/usr/local/lib/python3.10/site-packages/ozmo/__init__.py", line 862, in _handle_ctl_api
    if 'resp' in message:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by sh00t2kill** [comment]
No issue -- i think i just needed to wait longer after the robot was back online -- it started working.
